# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 757btc.org (Meet every 2nd Saturday of the month)
email: 757btc@gmail.com #not a legit email lol
description: >- # this means to ignore newlines until "baseurl:"
  Collaborating and educating on Bitcoin, Nostr and Freedom Tech in Hampton Roads Virginia. We announce our meetings at the beginning of each month and meet on the 2nd Saturday of each month.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.757btc.org" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  757btc
header_feature_image: assets/img/mermaid-bg.png
header_feature_image_responsive: true
header_text: Collaborating and Educating on Bitcoin, Nostr and Freedom Tech in Hampton Roads Virginia
footer_text: made with &#x1F9E1; by <a href="https://primal.net/p/npub1txh7f5wew26f56mps7l2gavgj0c9dnjj946a25ta7amgc6eqku6qwmwx64">@cnix</a>
color_theme: auto
# Build settings
markdown: kramdown
# theme: minima
remote_theme: sylhare/Type-on-Strap
post_navigation: true
paginate: 10
paginate_path: "posts/page:num"
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
include: [".well-known"]
